# Generated by Django 5.0.4 on 2024-04-16 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_alter_order_customer_alter_shippingaddress_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cat',
            new_name='category',
        ),
    ]
